### ISSUE TITLE
修改博客内容报错

### ISSUE THREAD

**Issue by yangxupei** [liangyd1024/goblog#1]
使用markdown编辑时报，系统繁忙。
编辑内容：
### 第一篇博客
----
#### 慌得一批的毕业生
	魔都打酱油
	继续打酱油

错误信息：
[goblog]2019/01/23 10:28:44.538479 base_controller.go:66: call PanicHandler errInfo:unexpected end of JSON input,err_type:string,stack:goroutine 342 [running]:

**Comment by liangyd1024** [comment]
错误现象显示是服务端接收数据收到了大小限制，查看beego.conf配置文件

![image](https://user-images.githubusercontent.com/5831731/51580970-4ab03100-1f01-11e9-8182-94c1afe29615.png)

发现有个配置项MaxMemory = 1024，此配置项是配置服务端接收的数据量的大小，从beego源码看此配置项默认值为1<<26,单位不是想象中的M

![image](https://user-images.githubusercontent.com/5831731/51581216-15f0a980-1f02-11e9-8d10-f294cc1ba114.png)

修改此配置项大小或者将此配置项注释掉使用默认值64M此问题解决

这里发现beego中两处不合理的地方：
1、这个配置项的单位感觉不是很人性化
2、这个配置项的命名会让人误以为是应用可使用的最大内存，而实际是服务端能接受每次请求的最大数据量的大小
