### ISSUE TITLE
项目依赖关系

### ISSUE THREAD

**Issue by Jeremy-boo** [liangyd1024/goblog#3]
（1）本地环境golang1.13.1,用你原先go.mod 下载依赖 根据go.mod  下载这个包github.com/go-ego/riot 有点问题，应该是包的版本有改变； 然后我删除了你的go.mod，直接 go mod init 然后在vendor 依赖下载成功，项目启动成功 但是访问 http://127.0.0.1:9090/admin/login 404

**Comment by Jeremy-boo** [comment]
找到问题了 beego 注册路由没有成功 刚准备学习下beego  感谢这个项目

**Comment by liangyd1024** [comment]
好的，有问题可以随时交流

**Comment by liangyd1024** [comment]
@Jeremy-boo 好的 ，有问题可以随时交流

**Comment by Jeremy-boo** [comment]
关于beego的自动注册路由 官网是不是bug啊，自动注册路由一直注册不全

**Comment by liangyd1024** [comment]
注册不全是啥意思 ，他会自动生成路由的文件你如果有新加路由配置，先把原来生成的删掉看看

**Comment by Jeremy-boo** [comment]
> 注册不全是啥意思 ，他会自动生成路由的文件你如果有新加路由配置，先把原来生成的删掉看看

就是将原先自动生成路由删除了，然后重新生成，总有几个的 controller的路由没有生成到路由文件，已经将runmod改成了dev,目前正在抽空研究中
